// frontend/src/app/components/dashboard/dashboard.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MonitoringDashboardComponent } from '../monitoring-dashboard/monitoring-dashboard.component';
import { TabNavigationComponent } from '../tab-navigation/tab-navigation.component';
import { TransactionHistoryComponent } from '../transaction-history/transaction-history.component';
import { AnalyticsComponent } from '../analytics/analytics.component';

interface Transaction {
  transaction_id: string;
  amount: number;
  merchant: string;
  currency: string;
  risk_score: number;
  status: string;
  timestamp?: string;
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, FormsModule, MonitoringDashboardComponent, TabNavigationComponent, TransactionHistoryComponent, AnalyticsComponent],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  @Input() token: string | null = null;
  @Output() logout = new EventEmitter<void>();

  transaction = { amount: '', merchant: '', currency: 'USD' };
  result: any = null;
  loading = false;
  transactions: Transaction[] = [];
  activeTab = 'dashboard';
  loadingTransactions = false;

  ngOnInit() {
    this.fetchTransactions();
  }

  deleteTransaction(transactionId: string) {
    this.transactions = this.transactions.filter(t => t.transaction_id !== transactionId);
  }

  async fetchTransactions() {
    if (!this.token) return;
    
    this.loadingTransactions = true;
    try {
      const response = await fetch('https://lpf1gn8aia.execute-api.us-east-1.amazonaws.com/dev/transactions', {
        method: 'GET',
        headers: {
          'Authorization': `Bearer ${this.token}`,
          'Content-Type': 'application/json'
        }
      });
      
      if (response.ok) {
        const data = await response.json();
        this.transactions = data.transactions || [];
      } else {
        console.error('Failed to fetch transactions:', response.status);
      }
    } catch (error) {
      console.error('Error fetching transactions:', error);
    } finally {
      this.loadingTransactions = false;
    }
  }

  async handleSubmit() {
    this.loading = true;
    
    try {
      if (!this.token) {
        throw new Error('No authentication token');
      }
      
      const response = await fetch('https://lpf1gn8aia.execute-api.us-east-1.amazonaws.com/dev/transaction', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${this.token}`
        },
        body: JSON.stringify(this.transaction)
      });
      
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }
      
      const data = await response.json();
      this.result = data;
      
      if (data.transaction_id) {
        await this.fetchTransactions();
      }
    } catch (error: any) {
      console.error('Transaction error:', error);
      this.result = { error: 'Failed to process transaction' };
    } finally {
      this.loading = false;
    }
  }

  onTabChange(tab: string) {
    this.activeTab = tab;
  }

  onLogout() {
    this.logout.emit();
  }
}
<div class="dashboard">
  <div class="dashboard-header">
    <h2>Transaction Monitor</h2>
    <button class="signout-btn" (click)="onLogout()">
      Sign Out
    </button>
  </div>
  
  <app-tab-navigation 
    [activeTab]="activeTab" 
    (tabChange)="onTabChange($event)">
  </app-tab-navigation>
  
  <div class="tab-content">
    <!-- Dashboard Tab -->
    <div *ngIf="activeTab === 'dashboard'">
      <app-monitoring-dashboard [transactions]="transactions"></app-monitoring-dashboard>
    </div>

    <!-- Submit Transaction Tab -->
    <div *ngIf="activeTab === 'transactions'">
      <form (ngSubmit)="handleSubmit()" class="transaction-form">
        <div class="form-group">
          <label>Amount:</label>
          <input
            type="number"
            step="0.01"
            [(ngModel)]="transaction.amount"
            name="amount"
            required
          />
        </div>
        
        <div class="form-group">
          <label>Merchant:</label>
          <input
            type="text"
            [(ngModel)]="transaction.merchant"
            name="merchant"
            required
          />
        </div>
        
        <div class="form-group">
          <label>Currency:</label>
          <select
            [(ngModel)]="transaction.currency"
            name="currency"
          >
            <option value="CAD">CAD - Canadian Dollar</option>
            <option value="EUR">EUR - Euro</option>
            <option value="GBP">GBP - British Pound</option>
            <option value="GHS">GHS - Ghana Cedi</option>
            <option value="INR">INR - Indian Rupee</option>
            <option value="JPY">JPY - Japanese Yen</option>
            <option value="KES">KES - Kenyan Shilling</option>
            <option value="NGN">NGN - Nigerian Naira</option>
            <option value="USD">USD - US Dollar</option>
            <option value="ZAR">ZAR - South African Rand</option>
          </select>
        </div>
        
        <button type="submit" [disabled]="loading">
          {{ loading ? 'Processing...' : 'Submit Transaction' }}
        </button>
      </form>
      
      <div class="result" [ngClass]="{'error': result?.error, 'success': !result?.error}" *ngIf="result">
        <div *ngIf="result.error">
          <p>Error: {{ result.error }}</p>
        </div>
        <div *ngIf="!result.error">
          <p>Transaction ID: {{ result.transaction_id }}</p>
          <p>Risk Score: {{ result.risk_score }}</p>
          <p>Status: {{ result.status }}</p>
        </div>
      </div>
    </div>

    <!-- Analytics Tab -->
    <div *ngIf="activeTab === 'analytics'">
      <app-analytics [transactions]="transactions"></app-analytics>
    </div>

    <!-- Transaction History Tab -->
    <div *ngIf="activeTab === 'history'">
      <app-transaction-history 
        [transactions]="transactions" 
        (delete)="deleteTransaction($event)">
      </app-transaction-history>
    </div>
  </div>
</div>

// frontend/src/components/Dashboard.jsx
import React, { useState } from "react";
import { fetchAuthSession } from "aws-amplify/auth";

function Dashboard() {
  const [transaction, setTransaction] = useState({ amount: '', merchant: '', currency: 'USD' });
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    
    try {
      const session = await fetchAuthSession();
      const token = session.tokens?.idToken?.toString();
      
      const response = await fetch('https://lpf1gn8aia.execute-api.us-east-1.amazonaws.com/dev/transaction', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(transaction)
      });
      
      const data = await response.json();
      setResult(data);
    } catch (error) {
      console.error('Transaction error:', error);
      setResult({ error: 'Failed to process transaction' });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="dashboard">
      <h2>📊 Transaction Monitor</h2>
      
      <form onSubmit={handleSubmit} className="transaction-form">
        <div className="form-group">
          <label>Amount:</label>
          <input
            type="number"
            step="0.01"
            value={transaction.amount}
            onChange={(e) => setTransaction({...transaction, amount: e.target.value})}
            required
          />
        </div>
        
        <div className="form-group">
          <label>Merchant:</label>
          <input
            type="text"
            value={transaction.merchant}
            onChange={(e) => setTransaction({...transaction, merchant: e.target.value})}
            required
          />
        </div>
        
        <div className="form-group">
          <label>Currency:</label>
          <select
            value={transaction.currency}
            onChange={(e) => setTransaction({...transaction, currency: e.target.value})}
          >
            <option value="USD">USD</option>
            <option value="EUR">EUR</option>
            <option value="GBP">GBP</option>
          </select>
        </div>
        
        <button type="submit" disabled={loading}>
          {loading ? 'Processing...' : 'Submit Transaction'}
        </button>
      </form>
      
      {result && (
        <div className={`result ${result.error ? 'error' : 'success'}`}>
          {result.error ? (
            <p>❌ Error: {result.error}</p>
          ) : (
            <div>
              <p>✅ Transaction ID: {result.transaction_id}</p>
              <p>🎯 Risk Score: {result.risk_score}</p>
              <p>📊 Status: {result.status}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default Dashboard;
